provide executor via porting package
eclipse/microprofile-telemetry pull request #183
Opened 2024-06-10 13:12 UTC by benjamin-confino

This creates a new module called `porting` that makes it possible to reflexively import classes provided by the integrator to run the TCK. To import a class you: 

- Put a file META-INF/microprofile-telemetry-tck.properties on the classpath to point to the class.
- Put the class on the classpath when the test is running. 

Currently this is used to import an impl of `Executor` so integrators than run tests that use concurrency

2024-06-10 13:18 UTC, benjamin-confino commented
fixes #140

2024-06-11 07:59 UTC, pdudits approved these changes
While this works a simpler implementation would have been replacing the `@Resource` with `@Inject` and require implementor to provide appropriate producer by means of e. g. Arquillian extension.

2024-06-11 21:13 UTC, Emily-Jiang commented on tck/porting/pom.xml
> +    <name>MicroProfile Telemetry Metrics Porting</name>
```suggestion
    <name>MicroProfile Telemetry Porting Executor</name>
```

2024-06-11 21:17 UTC, Emily-Jiang requested changes
You need to copy all of the files under resources/META-INF including the empty file `tck`

2024-06-12 21:19 UTC, Emily-Jiang commented on tck/tracing/pom.xml
> +        <dependency>
These lines should be deleted.

2024-06-12 21:48 UTC, donbourne commented on tck/tracing/README.adoc
> +Although support for JAX-RS server async programming models is not optional, these tests require you to provide an exector. <<Executor, See the section on providing an executor>>
exector -> executor

2024-06-13 13:22 UTC, merged