Update TCK to test for all required REST span properties
eclipse/microprofile-telemetry pull request #95
Opened 2023-06-06 12:42 UTC by pdudits

This follows Semantic Conventions 1.19, verifying most of required and conditionally required arguments.

* Specific values of span name is not checked, rather absence of high-cardinality parts of requests
* `net.host.name` and `net.host.port` are required for server Rest spans
* `http.route` is required for server Rest spans (normally optional, but "is required when server framework has concept of route", which Jakarta Rest has)
* `net.peer.name` and `net.peer.host` are required for client Rest spans
* error status of span is required for certain 4xx and 5xx requests

Fixes #86, #44.

Timing-dependant selections of span were for now replaced with kind-related ones, which work fine for existing tests.

2023-06-08 15:42 UTC, yasmin-aumeeruddy commented
The tests here look good. I think we now test all of the HTTP semantic attributes

2023-06-16 08:20 UTC, Emily-Jiang approved these changes
LGTM! Thanks @pdudits !

2023-06-16 08:36 UTC, Emily-Jiang commented
@pdudits the changes failed the build with the following errors:

> Error:  Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.22.0:validate (default-cli) on project microprofile-telemetry-tracing-tck: File '/home/runner/work/microprofile-telemetry/microprofile-telemetry/tracing/tck/src/main/java/org/eclipse/microprofile/telemetry/tracing/tck/rest/RestClientSpanTest.java' has not been previously formatted. Please format file (for example by invoking `mvn -f tracing/tck net.revelc.code.formatter:formatter-maven-plugin:2.22.0:format`) and commit before running validation! -> [Help 1]
It's the formatting issue. Please run `mvn package` and you should see the file formats being updated.

2023-06-16 08:37 UTC, Emily-Jiang requested changes
The code looks good! Need to fix the formatting.

2023-06-27 10:19 UTC, Emily-Jiang commented
@pdudits 
still got the same error:

> Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.22.0:validate (default-cli) on project microprofile-telemetry-tracing-tck: File '/home/runner/work/microprofile-telemetry/microprofile-telemetry/tracing/tck/src/main/java/org/eclipse/microprofile/telemetry/tracing/tck/rest/RestClientSpanTest.java' has not been previously formatted. Please format file (for example by invoking `mvn -f tracing/tck net.revelc.code.formatter:formatter-maven-plugin:2.22.0:format`) and commit before running validation! -> [Help 1]

2023-06-27 11:16 UTC, pdudits commented
I cannot reproduce the formatting error locally. Exact same formatter validation passes on my machine, invoking formatter plugin doesn't change any files.

2023-06-27 12:35 UTC, Emily-Jiang commented
> I cannot reproduce the formatting error locally. Exact same formatter validation passes on my machine, invoking formatter plugin doesn't change any files.
> 
> Verified once more in codespaces. No issues reported in completely clean environment either.

same here.

2023-06-27 13:04 UTC, Emily-Jiang commented
> I rebased, as Action is executing on merge result, and it can be git introducing some whitespace.

okay, thanks! I kicked off a build again Let's see how it goes. If not, I will update the workflow.

2023-06-27 13:16 UTC, Emily-Jiang approved these changes
Thank you @pdudits ! Your rebase did the trick!

2023-06-27 13:16 UTC, merged